trigger:
  - master

pool:
  vmImage: "windows-latest"

steps:
  - script: composer install --no-interaction --prefer-dist
    displayName: composer install

  - bash: |
      export PATH=$PATH:$CHROMEWEBDRIVER
      java -jar $SELENIUM_JAR_PATH &
    displayName: Start selenium

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: |
        export HOST='$(HOST)'
        export FORM_ID="$(FORM_ID)"
        export FAVOURITE_FOOD='$(FAVOURITE_FOOD)'
        export EMAIL_SENDER="$(EMAIL_SENDER)"
        bin/behat -f pretty -o std -f junit -o reports
    displayName: Run Tests

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "reports/default.xml"
      failTaskOnFailedTests: true
      testRunTitle: "Test Behat"
      buildPlatform: "ubuntu"
    condition: always()
